# Makefile.Vx
TOP = ../../../..
include $(TOP)/config/CONFIG_APP

RECTYPES += genSubRecord.h
DBDEXPAND = appInclude.dbd
DBDNAME   = app.dbd
SRCS.c   += ../genSubRecord.c
LIBOBJS  += genSubRecord.o
LIBNAME   = genSubLib
INSTALLS += iocCore seq

include ../baseLIBOBJS

include $(TOP)/config/RULES.Vx
